main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import (
    LedgerListView,
    LedgerUpdateView,
    LedgerDetailView,
    # LedgerCreateView,
    PersonListView,
    ItemListView,
    ItemUpdateView,
    ItemDetailView,
    ItemCreateView,
    PersonDetailView,
    ledger_create,
    LedgerListJson,
    ItemListJson,
    PersonListJson,
    OrderListJson,
    PersonUpdateView,
    OrderUpdateView,
    export_csv_items,
    export_csv_ledgers,
    export_csv_persons,
    export_csv_person_ledger,
    OrderItemCreateView
    # ImageModalTemplateView
)

app_name='main'

urlpatterns=[
    path('foo/', TemplateView.as_view(template_name='main/base2.html')),
    path('foo2/', TemplateView.as_view(template_name='main/foo2.html')),
    path("table/", TemplateView.as_view(template_name='main/table.html'), name="table"),

    path("i/<int:pk>", ItemDetailView.as_view(), name="item_detail"),
    path("i/<int:pk>/update", ItemUpdateView.as_view(), name="item_update"),
    path("i/create/", ItemCreateView.as_view(), name="item_create"),
    path("i/", ItemListView.as_view(), name="item_list"),
    path("i/msg/<str:msg>", ItemListView.as_view(), name="item_list"),
    path("i/data", ItemListJson.as_view(), name="item_list_json"),

    path("u/<int:pk>", PersonDetailView.as_view(), name="person_detail"),
    path("u/", PersonListView.as_view(), name="person_list"),
    path("u/data/", PersonListJson.as_view(), name="person_list_json"),
    path("u/<int:pk>/update", PersonUpdateView.as_view(), name="person_update"),

    path("login/", auth_views.LoginView.as_view(template_name='main/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name='main/login.html'), name="logout"),

    path("", LedgerListView.as_view(),name='homepage'),
    path("l/msg/<str:msg>", LedgerListView.as_view(),name='homepage'),
    path('l/data/', LedgerListJson.as_view(), name='ledger_list_json'),
    path("l/<int:pk>/data", OrderListJson.as_view(), name="order_list_json"),
    path("l/<int:pk>", LedgerDetailView.as_view(), name="ledger_detail"),
    path("l/<int:pk>/update", LedgerUpdateView.as_view(), name="ledger_update"),
    path("o/<int:pk>/update", OrderUpdateView.as_view(), name="ledger_order_update"),# l/<int:pk>/
    path("l/create", ledger_create, name="ledger_create"),
    path("o/update/<int:pk>", OrderItemCreateView.as_view(), name="order_item_create"),

    path("export-csv-items", export_csv_items, name="export_csv_items"),
    path("export-csv-ledgers", export_csv_ledgers, name="export_csv_ledgers"),
    path("export-csv-persons", export_csv_persons, name="export_csv_persons"),
    path("export-csv-person-ledger/<int:pk>", export_csv_person_ledger, name="export_csv_person_ledger"),

    # path("i/<int:pk>/img", ImageModalTemplateView.as_view(), name="image_modal")
]

tekinoto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("searchableselect/", include('searchableselect.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.handler404'

main/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
# from django.db.models.signals import pre_save, post_save
# from django.dispatch import receiver
from PIL import Image


class LedgerQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for obj in self:
            obj.img.delete()
        super(LedgerQuerySet, self).delete(*args, **kwargs)

class Item(models.Model):
    name  = models.CharField(max_length=255,verbose_name= ('Parça İsmi'), unique=True) # make it unique
    price = models.DecimalField(max_digits=7,decimal_places=2,verbose_name= ('Fiyat'))
    stock = models.SmallIntegerField(null=True, blank=True,verbose_name= ('Stok (Zorunlu değil)'))
    image = models.ImageField(default='default.png',upload_to='item_pics',verbose_name= ('Resim (Zorunlu değil)'))

    def __str__(self):
        return f'{self.name} - {self.price} TL'
    
    def get_absolute_url(self,*args,**kwargs):
        return reverse("main:item_detail", kwargs={"pk": self.pk})
    
    def save(self,*args,**kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
        
    class Meta:
        verbose_name = 'Parça'
        verbose_name_plural = 'Parçalar'
        ordering = ['name']


class OrderItem(models.Model):
    item   = models.ForeignKey('main.Item',on_delete=models.CASCADE, verbose_name=('Parca'))  # related_name='order'
    person = models.ForeignKey('main.Person', on_delete=models.CASCADE)
    amount = models.SmallIntegerField(default=1, verbose_name=('Adet'))
    
    def __str__(self):
        return f'{self.person} - {self.item} TL - {self.amount} adet'


class Order(models.Model):
    person          = models.ForeignKey('main.Person',related_name='orders' ,on_delete=models.CASCADE)
    items           = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    timestamp       = models.DateField(auto_now_add=True)
    item_sale_price = models.SmallIntegerField(null=True,blank=True)
    total           = models.SmallIntegerField(null=True,blank=True) # make it decimalfield ?
    paid_amount     = models.SmallIntegerField(default=0,blank=True,verbose_name= ('Ödenen miktar'))
    is_paid         = models.BooleanField(default=False,verbose_name= ('Ödendi mi ?'))
    #ledger many to many ?

    def save(self, *args, **kwargs):
        self.total = self.items.amount*self.items.item.price
        self.item_sale_price = self.items.item.price
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.person} - {self.items} - {self.timestamp}'
     

class Ledger(models.Model):
    objects       = LedgerQuerySet.as_manager()
    person        = models.OneToOneField("main.Person", related_name="ledger", on_delete=models.CASCADE)
    orders        = models.ManyToManyField(Order)  # models.ForeignKey('main.Order', related_name='ledger', on_delete=models.CASCADE)
    last_modified = models.DateField(auto_now=True)
    timestamp     = models.DateField(auto_now_add=True)

    # class Meta:
    #     sort by last modified
    
    def __str__(self):
        return f'{self.person}' # - {self.total}
    
    def get_absolute_url(self):
        return reverse("main:ledger_detail", kwargs={"pk": self.pk})
    
    def delete(self):
        if self.orders:
            for order in self.orders.all():
                order.items.delete()
                order.delete()
        super(Ledger,self).delete()
        
        


class Person(models.Model):
    fullname      = models.CharField(max_length=100, unique=True,verbose_name= ('Ad Soyad'))
    phone_number  = models.CharField(max_length=11,null=True, blank=True, unique=True,verbose_name= ('Telefon (Zorunlu Değil)'))
    # phone_number  = models.PhoneNumberField(null=True, blank=True, unique=True)

    def __str__(self):
        return f'{self.fullname}'

    def get_absolute_url(self,*args,**kwargs):
        return reverse("main:person_detail", kwargs={"pk": self.pk})

main/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum

# from django.template.loader import render_to_string
# from weasyprint import HTML
# import tempfile
# from django.db.models import Sum

import datetime
import csv

from django_datatables_view.base_datatable_view import BaseDatatableView

from .models import Ledger, Item, Person, Order, OrderItem
from .forms import OrderItemForm, LedgerForm, ItemForm, PersonForm, OrderUpdateForm  # OrderForm

from django.shortcuts import render
from django.template import RequestContext


def handler404(request, exception, template_name="main/404.html"):
    response = render(request,template_name)
    response.status_code = 404
    return response


@method_decorator(login_required, name='dispatch')
class LedgerListJson(BaseDatatableView):
    # The model we're going to show
    model = Ledger

    columns = ['person', 'total', 'last_modified']
    order_columns = ['person', 'total', 'last_modified']
    max_display_length = 500

    def get_initial_queryset(self):
        # .filter(orders__is_paid=False)
        return Ledger.objects.annotate(total=Sum('orders__total')-Sum('orders__paid_amount'))

    def filter_queryset(self, qs):
        # use request parameters to filter queryset
        # simple example:
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(person__fullname__icontains=search)
        return qs

    # def filter_queryset(self, qs):
    #     search = self.request.GET.get('search[value]', None)
    #     print(self.request)
    #     if search:
    #         qs = qs.filter(person__icontains=search)
    #     return qs

    def render_column(self, row, column):
        # We want to render user as a custom column
        if column == 'total':
            # debt = sum([order.total-order.paid_amount for order in row.orders.all()
            #            if not order.is_paid])
            if row.total is not None:
                return escape(f'{ row.total} TL')
            return escape('-')
        if column == 'last_modified':
            return escape(f'{ row.last_modified}')
        else:
            return super(LedgerListJson, self).render_column(row, column)


@method_decorator(login_required, name='dispatch')
class ItemListJson(BaseDatatableView):
    # The model we're going to show
    model = Item

    columns = ['name', 'price', 'stock', 'image']
    order_columns = ['name', 'price', 'stock', '']
    max_display_length = 500

    def render_column(self, row, column):
        # i recommend change 'flat_house.house_block.block_name' to 'address'
        modal = """<div class="modal fade" id="exampleModal{0}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">{1}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col">
                                            <img src="{2}" alt="Resim yok" style="max-width: 100%; max-height: 100%;">
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                                </div>
                            </div>
                        </div>
                    </div>""".format(row.id,row.name,row.image.url)
        if column == 'name':
            return '<a href="{0}">{1}</a>'.format(reverse('main:item_update', kwargs={'pk': row.id}), row.name)
        elif column == 'price':
            return escape(f'{row.price} TL')
        elif column == 'stock':
            if row.stock:
                return escape(f'{row.stock}')
            return escape('-')
        elif column == 'image':
            return '<button type="anchor" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{0}">Resim</button> {1}'.format(row.id, modal)
            # return '<a href="{0}" data-toggle="modal" data-target="#exampleModal{1}">resim</a>'.format(reverse('main:image_modal', kwargs={'pk': row.id}),row.id)
        else:
            return super(ItemListJson, self).render_column(row, column)


@method_decorator(login_required, name='dispatch')
class PersonListJson(BaseDatatableView):
    # The model we're going to show
    model = Person
    # datatable_options = {
    #         'columns': [
    #             'fullname',
    #             'phone_number',
    #         ],
    #     }

    # def get_total(self, instance, *args, **kwargs):
    #     orders = Order.objects.filter(person_id = self.model.id).filter(is_paid=False)
    #     return ", ".join(sum([order.total for order in orders]))
    
    columns = ['fullname', 'total', 'phone_number']
    order_columns = ['fullname', 'total', '']
    max_display_length = 500

    # datatable_options = {
    #         'columns': [
    #             'fullname',
    #             ("timestamp",'ledger__timestamp'),
    #             'phone_number',
    #         ],
    #         'unsortable_columns':['timestamp','phone_number']
    #     }

    def get_initial_queryset(self):
        # .filter(orders__is_paid=False)
        return Person.objects.annotate(total=Sum('orders__total')-Sum('orders__paid_amount'))

    def render_column(self, row, column):
        # i recommend change 'flat_house.house_block.block_name' to 'address'
        if column == 'fullname':
            return '<a href="{0}">{1}</a>'.format(f'{row.id}/update', row.fullname)
        elif column == 'phone_number':
            if row.phone_number:
                return escape(f'{row.phone_number}')
            return escape('Yok')
        if column == 'total':
            # link = 'l/{0}'.format(row.id)
            # link = ''
            # debts = [order.total for order in Ledger.objects.filter(
            #     person=row).first().orders.all() if order.total is not None]
            if row.total is not None:
                return escape(f'{ row.total} TL')
            return escape('-')
            # return '<a href="{0}">{1}</a>'.format(link, sum(debts))
        else:
            return super(PersonListJson, self).render_column(row, column)


@method_decorator(login_required, name='dispatch')
class OrderListJson(BaseDatatableView):
    # The model we're going to show
    model = Order

    columns       = ['name', 'price', 'sale_price', 'amount','total','paid_amount', 'remaining', 'timestamp', 'is_paid']
    order_columns = ['', '', '', '','total', '', '', 'timestamp', 'is_paid']
    max_display_length = 500


    def get_initial_queryset(self):
        orders = get_object_or_404(Ledger, person_id=self.kwargs.get('pk')).orders.all()
        return orders

    def filter_queryset(self, qs):
        # use request parameters to filter queryset
        # simple example:
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(items__item__name__icontains=search)
        return qs
    #     # more advanced example
    #     # filter_customer = self.request.GET.get('customer', None)

    #     # if filter_customer:
    #     #     customer_parts = filter_customer.split(' ')
    #     #     qs_params = None
    #     #     for part in customer_parts:
    #     #         q = Q(customer_firstname__istartswith=part)|Q(customer_lastname__istartswith=part)
    #     #         qs_params = qs_params | q if qs_params else q
    #     #     qs = qs.filter(qs_params)
       

    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for order in qs:
            if order.is_paid:
                json_data.append([
                    '<s><a href="{0}">{1}</s> (Ödendi)</a>'.format(reverse('main:ledger_order_update', kwargs={"pk": order.id}),order.items.item.name),  # escape HTML for security reasons
                    "<s>{0}</s>".format(f'{order.items.item.price} TL'),  # escape HTML for security reasons
                    "<s>{0}</s>".format(f'{order.item_sale_price} TL'),
                    "<s>{0}</s>".format(order.items.amount),
                    "<s>{0}</s>".format(f'{order.total} TL'),
                    "<s>{0}</s>".format(f'{order.paid_amount} TL'),
                    "<s>{0}</s>".format(f'{order.total - order.paid_amount} TL' if not order.is_paid else '0 TL'),
                    "<s>{0}</s>".format(order.timestamp),
                    "{0}".format('Evet' if order.is_paid else 'Hayır'),
                ])
            else:
                json_data.append([
                    '<a href="{0}">{1}</a>'.format(reverse('main:ledger_order_update', kwargs={"pk": order.id}),order.items.item.name),  # escape HTML for security reasons
                    escape("{0}".format(f'{order.items.item.price} TL')),  # escape HTML for security reasons
                    escape("{0}".format(f'{order.item_sale_price} TL')),
                    escape("{0}".format(order.items.amount)),

main/templates/main/home.html
{% extends "main/base.html" %}
{% load main_extras %}

{% block nav_ledger %}<span class="sr-only">(current)</span> {% endblock nav_ledger %}

{% block title %}
<h1 class="h2">Hesap Defteri  &ensp;  <span class="h6">Toplam Alacak = {{ total|floatformat }} TL</span>&emsp;&emsp;&emsp;<span class="h4">{{request.path|removefirst:7}}</span></h1>
{% endblock title %}

{% if msg %} <h4>{{msg}}</h4>{% endif %}

{% block extract %}
{% comment %} {% with name="url" %}     
"{% url 'main:ledger_create' %}"
{% endwith %}
{% include 'main/snippets/extract_button.html' with url=url %} {% endcomment %}
<div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <a href="{% url 'main:export_csv_ledgers' %}" class="btn btn-sm btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16"
          height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
          <path
            d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
          <path
            d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
        </svg> &ensp;Dışa aktar&emsp;</a>
    </div>
  </div>
{% endblock extract %}

{% block col2 %}
<div class="container">
	<div class="row">
		<div class="col mx-auto">
			<a href="{% url 'main:ledger_create' %}" class="btn btn-secondary" id="newledger"><svg
					xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
					class="bi bi-plus-circle" viewBox="0 0 16 16">
					<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
					<path
						d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
				</svg> Hesap Defteri'ne </br> Yeni Kayit ekle</a>
		</div>
	</div>

	</br>

	<div class="row">
		<div class="col mx-auto">
			<a href="{% url 'main:item_create' %}" class="btn btn-secondary" id="newledger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
				<path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
				<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
			  </svg> Yeni Parça ekle</a>
		</div>
	</div>
</div>
{% endblock col2 %}

{% block content %}

{% comment %} <div class="alert alert-secondary" role="alert">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-3 col-md-3">
				<p class="text-left h6">Toplam Alacak = {{ total|floatformat }} TL</p>
			</div>
			<div class="col-6 col-md-6">
				<p class="text-left font-weight-bold h3">TEKIN OTO HESAP DEFTERI</p>
			</div>
			<div class="col-3 col-md-3">
				<p class="text-right h6"></p>
			</div>
		</div>
	</div>
</div> {% endcomment %}

<div class="container">
	<div class="row mt-4">
		<div class="col-12 mx-auto">
			<table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
				<thead>
					<tr>
						<th>Ad Soyad</th>
						<th>Toplam Borç</th>
						<th>Son İşlem Tarihi</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
	
	
	
	
	
	<script>
	
		$('#example').DataTable({
			"processing":true,  
        	"serverSide":true,
			ajax: "{% url 'main:ledger_list_json' %}",
			language:
			{
				"decimal": "",
				"emptyTable": "Henüz bir kayıt oluşturulmamış",
				"info": "Sıralamak için tablo başlıklarına tıkla</br>Düzenlemek için isme tıkla</br>_TOTAL_ kayıt arasından _START_ ile _END_ arasındaki kayıtlar gösteriliyor",
				"infoEmpty": "0 kayıt arasından 0 dan 0 kadar olanı gösteriliyor",
				"infoFiltered": "</br>(toplam _MAX_ kayıt arasından filtrelendi)",
				"infoPostFix": "",
				"thousands": ",",
				searchPlaceholder: "Ad veya soyad gir",
				"lengthMenu": "_MENU_ kayıt göster",
				"loadingRecords": "Yükleniyor...",
				"processing": "İşleniyor...",
				"search": "Ara:",
				"zeroRecords": "Aramanızla eşleşen öge bulunmamaktadır",
				"paginate": {
					"first": "İlk",
					"last": "Son",
					"next": "İleri",
					"previous": "Geri"
				},
				"aria": {
					"sortAscending": ": artan şekilde sıralama",
					"sortDescending": ": azalan şekilde sırala"
				}
			}
			// "columnDefs": [ {
			// 	"targets": 1,
			// 	"data": null,
			// 	"render": function(data,type,row) { return 0}
			// } ]
		});
		$('.dataTables_filter input[type="search"]').css(
			{ 'width': '350px', 'display': 'inline-block' }
		);
		var $a = $('<div class="col-sm-12 col-md-4"><a href="{% url "main:ledger_create" %}" class="btn btn-success btn-sm">&emsp;<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>&ensp;Yeni Kayıt Oluştur&emsp;</a></div>"' );
		$('#example_wrapper').find('.row').eq(0).addClass('d-flex justify-content-between');
		$($('#example_wrapper').find('.row')[0].children[0]).attr('class', 'col-sm-12 col-md-4');
		$($('#example_wrapper').find('.row')[0].children[1]).attr('class', 'col-sm-12 col-md-4');
		$('#example_wrapper').find('.row').eq(0).children().first().after($a);
		// var $elem = $('#example_wrapper').find('.row')[0].children;
		// $("#example_wrapper > row:nth-child(0)").after("<div>great things</div>");
		// // $("#controller > div:nth-child(" + (i) + ")").after("<div>great things</div>");
	
		// $('.dataTables_length').append($a);
	</script>
</div>


</div>



{% endblock content %}

main/templates/main/item_list.html
{% extends "main/base.html" %}
{% load main_extras %}



{% block title %}
<h1 class="h2">Parça Listesi&emsp;&emsp;&emsp;<span class="h4">{{request.path|removefirst:7}}</span></h1>
{% endblock title %}
{% if msg %} <h4>{{msg}}</h4>{% endif %}
{% block extract %}
<div class="btn-toolbar mb-2 mb-md-0">
	<div class="btn-group mr-2">
		<a href="{% url 'main:export_csv_items' %}" id="#printButton" class="btn btn-sm btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg"
				width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
				<path
					d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
				<path
					d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
			</svg> &ensp;Dışa aktar&emsp;</a>
	</div>
</div>
{% endblock extract %}

{% block content %}
<div class="container">
	<div class="row mt-4">
		<div class="col-12 mx-auto">
			<table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
				<thead>
					<tr>
						<th>Parça İsmi</th>
						<th>Fiyat</th>
						<th>Stok</th>
						<th>Resim</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>



	<script>
		var table = $('#example').DataTable({
			"processing":true,  
        	"serverSide":true,
			ajax: "{% url 'main:item_list_json' %}",
			// buttons: ['pdf'],
			columnDefs: [ { orderable: false, targets: [3] }],
            // order: [[ 4, 'asc' ], [ 8, 'asc' ], [ 7, 'asc' ]],
			language:
			{
				"decimal": "",
				"emptyTable": "Henüz bir kayıt oluşturulmamış",
				"info": "Sıralamak için tablo başlıklarına tıkla</br>Duzenlemek icin parca ismine tikla</br>_TOTAL_ kayıt arasından _START_ ile _END_ arasındaki kayıtlar gösteriliyor",
				"infoEmpty": "0 kayıt arasından 0 dan 0 kadar olanı gösteriliyor",
				"infoFiltered": "</br>(toplam _MAX_ kayıt arasından filtrelendi)",
				"infoPostFix": "",
				"thousands": ",",
				searchPlaceholder: "Parca ismi gir",
				"lengthMenu": "_MENU_ kayıt göster",
				"loadingRecords": "Yükleniyor...",
				"processing": "İşleniyor...",
				"search": "Ara:",
				"zeroRecords": "Aramanızla eşleşen öge bulunmamaktadır",
				"paginate": {
					"first": "İlk",
					"last": "Son",
					"next": "İleri",
					"previous": "Geri"
				},
				"aria": {
					"sortAscending": ": artan şekilde sıralama",
					"sortDescending": ": azalan şekilde sırala"
				}
			},
		});
		var target = $('.d-flex .btn-toolbar .btn-group');
		// table.buttons().container().appendTo(target);
		// $("#printButton").on("click", function () {
		// 	table.button('.buttons-pdf').trigger();
		// });

		$('.dataTables_filter input[type="search"]').css(
			{ 'width': '350px', 'display': 'inline-block' }
		);
		var $a = $('<div class="col-sm-12 col-md-4"><a href="{% url "main:item_create" %}" class="btn btn-success btn-sm">&emsp;<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>&ensp;Parça Ekle&emsp;</a></div>"');
		$('#example_wrapper').find('.row').eq(0).addClass('d-flex justify-content-between');
		$($('#example_wrapper').find('.row')[0].children[0]).attr('class', 'col-sm-12 col-md-4');
		$($('#example_wrapper').find('.row')[0].children[1]).attr('class', 'col-sm-12 col-md-4');
		$('#example_wrapper').find('.row').eq(0).children().first().after($a);
	</script>
</div>

{% endblock content %}

main/templates/main/orderitem_create.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<h1 class="h2">{{person}} hesabına Yeni Sipariş(Borç) Gir</h1>
{% endblock title %}



{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    </br>
    <button class="btn btn-primary"> Ekle </button>

</form>

<script>
    $(document).ready(function () {
        $('#id_item').select2({
            placeholder: "Aramak icin Parca ismini giriniz",
            allowClear: true
        });
    });

</script>

{% endblock content %}